# New cops
AllCops:
  NewCops: enable
  SuggestExtensions: false

# Miscelleneous
Layout/ClassStructure:
  Enabled: true
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/HeredocArgumentClosingParenthesis:
  Enabled: true
Style/CollectionMethods:
  Enabled: true

# RSpec
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/OpenStructUse:
  Exclude:
    - '**/*_spec.rb'

# Refactoring
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Line breaks
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodParameterLineBreaks:
  Enabled: true

# Katas
Lint/UnusedMethodArgument:
  Enabled: false
Lint/UselessAccessModifier:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Lint/UselessTimes:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
# Style/SingleLineDoEndBlock:
#   Enabled: false
Style/SoleNestedConditional:
  Enabled: false

# Disable annoyances
Layout/LineLength:
  Enabled: false
Metrics:
  Enabled: false
Naming:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/StructInheritance:
  Enabled: false
