require:
  - rubocop-performance
  - rubocop-rails

# New cops
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - '**/gilded_rose_old.rb'

# Miscelleneous
Layout/ClassStructure:
  Enabled: true
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/HeredocArgumentClosingParenthesis:
  Enabled: true
Style/CollectionMethods:
  Enabled: true

# RSpec
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/OpenStructUse:
  Exclude:
    - '**/*_spec.rb'
    - '**/*_test.rb'

# Refactoring
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Indentation
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

# Line breaks
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodParameterLineBreaks:
  Enabled: true

# Katas
Lint/UnusedMethodArgument:
  AutoCorrect: false
Lint/UselessAccessModifier:
  AutoCorrect: false
Lint/UselessAssignment:
  AutoCorrect: false
Lint/UselessTimes:
  AutoCorrect: false
Style/EmptyMethod:
  AutoCorrect: false
Style/GuardClause:
  AutoCorrect: false
Style/IdenticalConditionalBranches:
  AutoCorrect: false
Style/IfUnlessModifier:
  AutoCorrect: false
Style/SingleLineDoEndBlock:
  AutoCorrect: false
Style/SoleNestedConditional:
  AutoCorrect: false

# Disable annoyances
Layout/LineLength:
  Enabled: false
Metrics:
  Enabled: false
Naming:
  Enabled: false
Rails/Output:
  Enabled: false
Rails/Date:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/StructInheritance:
  Enabled: false
