#!/bin/zsh

source ~/.zshrc

echo "\nTerminating packmanager..."
pm_kill

echo "\nDisabling apps with browser integration..."
disable_apps

echo "\nTerminating chrome processes..."
kill_chrome

echo "\nTerminating ruby processes..."
killall -q ruby

echo "\nMarking packmanager test directories in rubymine..."
cd ~/src/packmanager && ruby_use && bundle --quiet && bundle exec ./development/rubymine/mark_directories.rb

echo "\nPrune docker..."
docker image prune -a -f && docker system prune -f

echo "\nUpdating private git repo..."
cd ~/root/projects/private && gaa && git commit -m "auto-update"; gp --quiet

echo "\nUpdating tldr..."
tldr --update

echo "\nUpdating dev-toolbox..."
cd ~/root/third_party/dev-toolbox && git pull --quiet

echo "\nUpdating oh-my-zsh-plugins..."
cd ~/.oh-my-zsh-custom && git pull --quiet

echo "\nDeleting stale branches of production-scheduling..."
cd ~/src/production-scheduling && git fetch -p --quiet && delete_stale_branches

echo "\nDeleting stale branches of packmanager..."
cd ~/src/packmanager && git fetch -p --quiet && delete_stale_branches

echo "\nUpdating rubygems system in default ruby..."
cd ~ && ruby_use && gem_update

echo "\nUpdating rubygems system in packmanager..."
cd ~/src/packmanager && ruby_use && gem_update && bundle_update && gco Gemfile.lock

echo "\nUpdating rubygems system in production-scheduling..."
cd ~/src/production-scheduling/backend && ruby_use && gem_update && bundle_update && gco Gemfile.lock

echo "\nUpdating homebrew..."
update_homebrew
