#!/usr/bin/env ruby

run_cmd =
  case
  when Dir.glob('test/*_test.rb').any?
    'ruby test/*_test.rb'
  when Dir.glob('*_test.rb').any?
    'ruby *_test.rb'
  when Dir.glob('**/*_spec.rb').any?
    'rspec .'
  when File.exist?('main.rb')
    'ruby main.rb'
  when File.exist?('scrap.rb')
    'ruby scrap.rb'
  else
    abort "No matching files to execute"
  end

full_cmd = "ag -g '\\.rb$' | entr -c -d -p -s 'rubocop -A; clear; #{run_cmd}'"

system full_cmd
