#!/bin/bash

trap "echo Exited!; exit;" SIGINT SIGTERM

watch_pattern="(app|lib|spec)/.*$1.*\.rb$"
echo $watch_pattern

while true; do
  ag -g "${watch_pattern}" | entr -c -d -p -s "bundle exec spring rspec $2"
done