#!/bin/bash

trap "echo Exited!; exit;" SIGINT SIGTERM

watch_pattern="(app|spec).*$1.*\.rb$"

echo $watch_pattern

while true; do
  ag -g "${watch_pattern}"
  ag -g "${watch_pattern}" | entr -c -d -p -s "bundle exec rspec $2"
done
